# Generated by Django 2.0.1 on 2018-01-27 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180126_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='get_notified',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='get_notified',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
