# Generated by Django 2.0.1 on 2018-01-29 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180129_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_notified',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
